GOOSE_PROVIDER: anthropic
OLLAMA_HOST: localhost
GOOSE_MODEL: claude-3-5-sonnet-latest
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  fetch:
    args:
    - mcp-server-fetch
    bundled: null
    cmd: uvx
    description: Web content fetching and processing capabilities
    enabled: true
    env_keys: []
    envs: {}
    name: Fetch
    timeout: 300
    type: stdio
  git:
    args:
    - mcp-server-git
    bundled: null
    cmd: uvx
    description: Git version control system integration
    enabled: true
    env_keys: []
    envs: {}
    name: Git
    timeout: 300
    type: stdio
  jetbrains:
    bundled: true
    display_name: Jetbrains
    enabled: false
    name: jetbrains
    timeout: 300
    type: builtin
  knowledgegraphmemory:
    args:
    - -y
    - '@modelcontextprotocol/server-memory'
    bundled: null
    cmd: npx
    description: Graph-based memory system for persistent knowledge storage
    enabled: true
    env_keys: []
    envs: {}
    name: Knowledge Graph Memory
    timeout: 300
    type: stdio
  memory:
    bundled: true
    display_name: Memory
    enabled: false
    name: memory
    timeout: 300
    type: builtin
  telnet:
    args:
    - -y
    - github:distantorigin/mcp-telnet
    bundled: null
    cmd: npx
    description: Connect to telnet services.
    enabled: true
    env_keys: []
    envs: {}
    name: Telnet
    timeout: 300
    type: stdio
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: true
    name: tutorial
    timeout: 300
    type: builtin
  vscode:
    args:
    - vscode-mcp-server
    bundled: null
    cmd: npx
    description: Provides a VSCode IDE integration for development workflows
    enabled: true
    env_keys: []
    envs: {}
    name: VSCode
    timeout: 300
    type: stdio
