#!/usr/bin/env sh

#######################
# SCRIPTING ADDITION #
#######################

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###################
# GLOBAL SETTINGS #
###################

# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#global-settings

yabai -m config \
    debug_output                   off            \
    external_bar                   all:30:0       \
    menubar_opacity                1.0            \
    mouse_follows_focus            off            \
    focus_follows_mouse            off            \
    display_arrangement_order      default        \
    window_origin_display          default        \
    window_placement               second_child   \
    window_zoom_persist            on             \
    window_shadow                  on             \
    window_opacity                 on             \
    window_opacity_duration        0.0            \
    active_window_opacity          0.95           \
    normal_window_opacity          0.90           \
    window_animation_duration      0.0            \
    window_animation_easing        ease_out_circ  \
    insert_feedback_color          0xFFF6E2B9     \
    split_ratio                    0.50           \
    split_type                     auto           \
    mouse_modifier                 fn             \
    mouse_action1                  move           \
    mouse_action2                  resize         \
    mouse_drop_action              swap           \
    layout                         bsp            \
    top_padding                    12             \
    bottom_padding                 12             \
    left_padding                   12             \
    right_padding                  12             \
    window_gap                     12             \
    auto_balance                   on

###########
# OPACITY #
###########

apps_full_opacity=(
    "Preview"
    "Google Chrome"
    "Avalonia Application"
    "Space Station 14 Launcher"
    "Space Station 14"
    "Draw Things"
    "The Sims 4"
)

for app in "${apps_full_opacity[@]}"; do
    yabai -m rule --add app="$app" opacity=1.0
done
