#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 all:30:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        0.95           \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \

# designated applications are fully opaque
yabai -m rule --add app="Preview" opacity=1.0
yabai -m rule --add app="Google Chrome" opacity=1.0
yabai -m rule --add app="Avalonia Application" opacity=1.0
yabai -m rule --add app="Space Station 14 Launcher" opacity=1.0
yabai -m rule --add app="Space Station 14" opacity=1.0
yabai -m rule --add app="Draw Things" opacity=1.0

echo "yabai configuration loaded.."
