#!/bin/bash
# Test for the WAKE-TIME SEAT IDENTITY header in session-start.sh
# (dotfiles-z10i) and its composer agents/lib/seat-identity.sh.
#
# What it guards. k50m resolved SESSION_WINDOW and left the seam UNCONSUMED;
# this is the consumer. The properties that matter are all about SILENCE and
# COST, because both fail invisibly:
#
#   - a REGISTERED window gets office + charter + laurels + constitution
#   - an UNREGISTERED window, and a session with no window at all, get ZERO
#     new output — not a warning, not a refusal, nothing (a scratch window is
#     the normal case, and 🚫 on every session start is fleet-wide noise)
#   - the composer is never even SPAWNED for a window the roster does not
#     mention (case 6 proves the pre-check mechanically, with a stub that
#     records its own invocation)
#   - every failure path degrades to silence and rc 0 — a hook that breaks
#     session start breaks every session on the machine
#
# Hook test convention (see test-session-start-window.sh): executable bash,
# non-zero exit = failed, PASS/FAIL summary on the last line.
#
# HERMETIC. A whole fixture TIER is built under a temp dir — its own
# seats.yml, its own refs/seats/ histories, its own $HOME, a mock `tmux` on
# PATH — so the real roster, the real histories and the real tmux server are
# never read and never written.

set -u

REPO_AGENTS="$(cd "$(dirname "$0")/../.." && pwd)"
PASS=0
FAIL=0
FAILED_NAMES=()
ok()  { PASS=$((PASS + 1)); }
bad() { FAIL=$((FAIL + 1)); FAILED_NAMES+=("$1"); }

BASE=$(mktemp -d)
trap 'chmod -R u+w "$BASE" 2>/dev/null; rm -rf "$BASE"' EXIT

# --- the fixture tier -------------------------------------------------------
TIER="$BASE/tier"
mkdir -p "$TIER/agents" "$TIER/refs/seats"
cp -r "$REPO_AGENTS/hooks" "$TIER/agents/hooks"
cp -r "$REPO_AGENTS/lib"   "$TIER/agents/lib"
HOOK="$TIER/agents/hooks/session-start.sh"
ROSTER="$TIER/agents/seats.yml"

cat > "$ROSTER" <<'YAML'
schema: 1
hosts: [test-host]
charter: null
taps:
  personal:
    type: claude
    config_dir: ~/.claude
    failover: []
seats:
  seat-alpha:
    charter-line: "fixture charter — the line the wake header must carry"
    office: "The Fixture"
    sigil: "🧪"
    home: ~/tmp
    model: sonnet
    effort: high
    tap: personal
    aliases: []
    history: refs/seats/seat-alpha.history.md
    schedules: []
YAML

# Histories are GENERATED by the only writer there is (seat-history.sh), never
# hand-written: a hand-written file would carry a wrong integrity checksum and
# this suite would be testing a shape the harness cannot actually produce.
SEATS_YML="$ROSTER" bash "$TIER/agents/lib/seat-history.sh" init \
  --dir "$TIER/refs/seats" >/dev/null || { echo "FIXTURE: history_init failed"; exit 1; }
SEATS_YML="$ROSTER" bash "$TIER/agents/lib/seat-history.sh" laurel \
  --seat seat-alpha --title "held the line under load" \
  --bead dotfiles-fixture --commit deadbee --why "fixture laurel, cited" \
  --date 2026-08-09 --dir "$TIER/refs/seats" >/dev/null \
  || { echo "FIXTURE: history_laurel failed"; exit 1; }

# --- mock tmux (same shape as test-session-start-window.sh's) ---------------
MOCKDIR="$BASE/mocktmux"
mkdir -p "$MOCKDIR"
cat > "$MOCKDIR/tmux" <<'EOF'
#!/bin/sh
case "$*" in
  *list-panes*pane_id*)     [ -n "${MOCK_PID:-}" ] && printf '%s %%99\n' "${MOCK_PID}" ;;
  *list-panes*window_name*) [ -n "${MOCK_PID:-}" ] && printf '%s %s\n' "${MOCK_PID}" "${MOCK_WIN:-}" ;;
  *display-message*)        [ -n "${MOCK_DISP:-}" ] && printf '%s\n' "${MOCK_DISP}" ;;
esac
exit 0
EOF
chmod +x "$MOCKDIR/tmux"

# --- a real repo for the hook to run in ------------------------------------
PROJ="$BASE/proj"
mkdir -p "$PROJ"
git -C "$PROJ" init -q -b main
git -C "$PROJ" config user.email t@t; git -C "$PROJ" config user.name t
echo seed > "$PROJ/seed"; git -C "$PROJ" add seed; git -C "$PROJ" commit -qm seed

# new_home: a fake $HOME with a real settings.json symlink (so the unrelated
# settings-symlink guard stays quiet) and a constitution to point at.
new_home() {
  local fh
  fh=$(mktemp -d "$BASE/home.XXXXXX")
  mkdir -p "$fh/dotfiles/claude" "$fh/.claude" "$fh/demesne/docs"
  printf '%s\n' '{}' > "$fh/dotfiles/claude/settings.json"
  ln -s "$fh/dotfiles/claude/settings.json" "$fh/.claude/settings.json"
  printf '# The Constitution of the Demesne\n' > "$fh/demesne/docs/constitution.md"
  printf '%s' "$fh"
}

# run_hook <fakehome> <log> [env assignments...] -> stdout+stderr combined.
# HANDOFF_WINDOW is the documented SESSION_WINDOW override seam (handoff-
# path.sh `_handoff_key` step 0), which is how each case names its window
# without a tmux server. CLAUDE_CODE_SESSION_ID + the lexicon dir are scrubbed
# per call for the reason test-session-start-window.sh documents: the sticky
# session->window cache is REAL and shared, and one case can otherwise seed a
# later case's answer.
run_hook() {
  local fh=$1 log=$2; shift 2
  local lexdir; lexdir=$(mktemp -d "$BASE/lex.XXXXXX")
  ( cd "$PROJ" && env -u TMUX_PANE -u TMUX -u HANDOFF_WINDOW -u SEAT_WINDOW \
      -u CLAUDE_CODE_SESSION_ID -u SEAT_HISTORY_DIR \
      HOME="$fh" HARNESS_SESSION_START_LOG="$log" \
      CLAUDE_LEXICON_STATE_DIR="$lexdir" SEATS_YML="$ROSTER" \
      GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null \
      PATH="$MOCKDIR:$PATH" \
      "$@" \
      bash "$HOOK" <<< '{"hook_event_name":"SessionStart","cwd":"'"$PROJ"'"}' 2>&1 )
}

# The four markers that make up a header. "no new output" means NONE of them.
has_header() { printf '%s' "$1" | grep -qF 'seat-alpha — The Fixture'; }
any_marker() {
  printf '%s' "$1" | grep -qE 'charter:|constitution:|🏅|🚫|— The Fixture'
}

# Case IDs lead every failure name: the mutation harness
# (test/mutate-seat-identity.sh) asserts that each mutant dies on the case(s)
# it NAMES, and it reads those ids out of this suite's failure lines.
#
# --- R: a REGISTERED window gets the full header ---------------------------
FH=$(new_home)
OUT1=$(run_hook "$FH" "$BASE/log1" HANDOFF_WINDOW=seat-alpha); RC1=$?
if has_header "$OUT1"; then ok; else
  bad "R1 registered: office line '🧪 seat-alpha — The Fixture' missing from the header"
fi
if printf '%s' "$OUT1" | grep -qF 'charter: fixture charter'; then ok; else
  bad "R2 registered: the seat's charter-line is missing from the header"
fi
if printf '%s' "$OUT1" | grep -qF '🏅 2026-08-09 · held the line under load'; then ok; else
  bad "R3 registered: the last laurel is missing (history_head is the laurel source)"
fi
if printf '%s' "$OUT1" | grep -qF "constitution: $FH/demesne/docs/constitution.md"; then ok; else
  bad "R4 registered: the constitution pointer is missing or points elsewhere"
fi
if [ "$RC1" -eq 0 ]; then ok; else
  bad "R5 registered: hook must exit 0, got rc=$RC1"
fi

# --- U: an UNREGISTERED window gets ZERO new output ------------------------
FH=$(new_home)
OUT2=$(run_hook "$FH" "$BASE/log2" HANDOFF_WINDOW=scratchpad); RC2=$?
if any_marker "$OUT2"; then
  bad "U1 unregistered: expected ZERO new output; got: $(printf '%s' "$OUT2" | grep -E 'charter:|constitution:|🏅|🚫|— The Fixture' | head -3)"
else ok; fi
if [ "$RC2" -eq 0 ]; then ok; else
  bad "U2 unregistered: hook must still exit 0, got rc=$RC2"
fi
if printf '%s' "$OUT2" | grep -qF '=== Session Context ==='; then ok; else
  bad "U3 unregistered: the normal session-start banner must still print"
fi

# --- P: a name that IS in the roster file but is NOT a seat ----------------
#     `personal` is a TAP, so it passes the cheap grep pre-check and reaches
#     the composer, which must resolve nothing and say nothing. This is the
#     case that separates "gated by grep" from "actually silent".
FH=$(new_home)
OUT3=$(run_hook "$FH" "$BASE/log3" HANDOFF_WINDOW=personal); RC3=$?
if any_marker "$OUT3"; then
  bad "P1 roster-word-not-a-seat: expected silence for 'personal'; got: $(printf '%s' "$OUT3" | grep -E 'charter:|constitution:|🏅|🚫|— The Fixture' | head -3)"
else ok; fi
if [ "$RC3" -eq 0 ]; then ok; else
  bad "P2 roster-word-not-a-seat: hook must exit 0, got rc=$RC3"
fi

# P3 — "ZERO new output" asserted as BYTE-IDENTICAL, not just marker-free.
# Same $HOME, same window, the only difference being whether the composer
# exists at all: an unresolvable seat must leave the session's context exactly
# as it was before this feature. A marker grep cannot see a stray blank line;
# this can.
OUT3B=$(mv "$TIER/agents/lib/seat-identity.sh" "$BASE/parked" \
        && run_hook "$FH" "$BASE/log3b" HANDOFF_WINDOW=personal)
mv "$BASE/parked" "$TIER/agents/lib/seat-identity.sh"
if [ "$OUT3" = "$OUT3B" ]; then ok; else
  bad "P3 roster-word-not-a-seat: output differs from a run with NO composer at all: $(diff <(printf '%s\n' "$OUT3B") <(printf '%s\n' "$OUT3") | head -5 | tr '\n' ' ')"
fi

# --- W: no window at all (no tmux answer, no override) ---------------------
FH=$(new_home)
OUT4=$(run_hook "$FH" "$BASE/log4"); RC4=$?
if grep -qF 'session window: <unresolved>' "$BASE/log4"; then ok; else
  bad "W1 no-window: fixture is wrong — SESSION_WINDOW should be unresolved here"
fi
if any_marker "$OUT4"; then
  bad "W2 no-window: a session with no window must get ZERO new output"
else ok; fi
if [ "$RC4" -eq 0 ]; then ok; else
  bad "W3 no-window: hook must exit 0, got rc=$RC4"
fi

# --- B: the composer is MISSING (a broken/partial install) -----------------
FH=$(new_home)
mv "$TIER/agents/lib/seat-identity.sh" "$BASE/seat-identity.parked"
OUT5=$(run_hook "$FH" "$BASE/log5" HANDOFF_WINDOW=seat-alpha); RC5=$?
mv "$BASE/seat-identity.parked" "$TIER/agents/lib/seat-identity.sh"
if [ "$RC5" -eq 0 ]; then ok; else
  bad "B1 missing-composer: hook must exit 0 when seat-identity.sh is absent, got rc=$RC5"
fi
if any_marker "$OUT5"; then
  bad "B2 missing-composer: expected silence, got header output"
else ok; fi
if printf '%s' "$OUT5" | grep -qF '=== Session Context ==='; then ok; else
  bad "B3 missing-composer: the normal session-start banner must still print"
fi

# --- 6. THE PRE-CHECK IS REAL: the composer is not even spawned for a window
#     the roster never mentions. A stub records every invocation; an
#     unregistered window must leave NO record, a registered one must leave
#     exactly one. Without this, "cheap" is an assertion in a comment.
STUB_LOG="$BASE/spawned.log"
mv "$TIER/agents/lib/seat-identity.sh" "$BASE/seat-identity.real"
cat > "$TIER/agents/lib/seat-identity.sh" <<EOF
#!/bin/bash
echo "spawned \$*" >> "$STUB_LOG"
exit 1
EOF
FH=$(new_home); run_hook "$FH" "$BASE/log6a" HANDOFF_WINDOW=scratchpad >/dev/null
if [ ! -s "$STUB_LOG" ]; then ok; else
  bad "G1 precheck: the composer was SPAWNED for an unregistered window ($(cat "$STUB_LOG"))"
fi
FH=$(new_home); run_hook "$FH" "$BASE/log6b" HANDOFF_WINDOW=seat-alpha >/dev/null
if [ "$(grep -c spawned "$STUB_LOG" 2>/dev/null || echo 0)" -eq 1 ]; then ok; else
  bad "G2 precheck: a REGISTERED window must spawn the composer exactly once (log: $(cat "$STUB_LOG" 2>/dev/null))"
fi
mv "$BASE/seat-identity.real" "$TIER/agents/lib/seat-identity.sh"

# --- C: the composer on its own: silent rc 1 for an unregistered window ----
COMP="$TIER/agents/lib/seat-identity.sh"
C_OUT=$(SEATS_YML="$ROSTER" SEAT_HISTORY_DIR="$TIER/refs/seats" SEAT_WINDOW=scratchpad \
        bash "$COMP" --laurels 3 2>&1); C_RC=$?
if [ "$C_RC" -ne 0 ] && [ -z "$C_OUT" ]; then ok; else
  bad "C1 composer: unregistered window must be silent with rc!=0; rc=$C_RC out='$C_OUT'"
fi

# --- 8. --laurels caps the injected history --------------------------------
#     A laurel that costs context in every session forever is a tax, not a
#     reward (9z7l): the cap is what keeps the header 3-5 lines as the record
#     grows. Two more laurels, then assert only one comes back at --laurels 1.
for d in 2026-08-10 2026-08-11; do
  SEATS_YML="$ROSTER" bash "$TIER/agents/lib/seat-history.sh" laurel \
    --seat seat-alpha --title "another one $d" --bead dotfiles-fixture \
    --commit deadbee --why "second fixture laurel" --date "$d" \
    --dir "$TIER/refs/seats" >/dev/null
done
CAP_OUT=$(SEATS_YML="$ROSTER" SEAT_HISTORY_DIR="$TIER/refs/seats" SEAT_WINDOW=seat-alpha \
          bash "$COMP" --laurels 1)
if [ "$(printf '%s\n' "$CAP_OUT" | grep -c '🏅')" -eq 1 ]; then ok; else
  bad "K1 cap: --laurels 1 must inject exactly one laurel, got $(printf '%s\n' "$CAP_OUT" | grep -c '🏅')"
fi
if [ "$(printf '%s\n' "$CAP_OUT" | wc -l)" -le 5 ]; then ok; else
  bad "K2 cap: the header must stay 3-5 lines, got $(printf '%s\n' "$CAP_OUT" | wc -l)"
fi

# --- N: no constitution on the box -> the pointer is OMITTED, not dangling -
FH=$(new_home); rm -rf "$FH/demesne"
N_OUT=$(env -u SEAT_CONSTITUTION HOME="$FH" SEATS_YML="$ROSTER" \
        SEAT_HISTORY_DIR="$TIER/refs/seats" SEAT_WINDOW=seat-alpha bash "$COMP")
if printf '%s' "$N_OUT" | grep -qF 'constitution:'; then
  bad "N1 no-constitution: a path that resolves nowhere must be omitted, not printed"
else ok; fi
if printf '%s' "$N_OUT" | grep -qF 'seat-alpha — The Fixture'; then ok; else
  bad "N2 no-constitution: the rest of the header must still print"
fi

# --- X: the CACHE — warm reads must be free, and must NOT go stale ---------
#     Composing the header costs a bash start and a python3 roster parse, so
#     the hook re-serves cached bytes while nothing they depended on has
#     moved. Both halves of that are silent when broken: a cache that never
#     hits costs every session ~200ms nobody notices, and a cache that never
#     EXPIRES serves last month's office forever. All three cases share one
#     $HOME on purpose — the cache lives under it.
FH=$(new_home)
OUT_X1=$(run_hook "$FH" "$BASE/logx1" HANDOFF_WINDOW=seat-alpha)
CDIR="$FH/.cache/seat-identity"
if [ -s "$CDIR/seat-alpha.header" ] && [ -s "$CDIR/seat-alpha.deps" ]; then ok; else
  bad "X1 cache: a resolved header must leave both <seat>.header and <seat>.deps (got: $(ls "$CDIR" 2>&1 | tr '\n' ' '))"
fi

# The warm-path probe is a recording `python3` on PATH, NOT a stub composer:
# the composer's own path is one of the deps it declares (an edit to it must
# expire every cached header), so swapping the file would legitimately
# invalidate the cache and the probe would measure itself. Shadowing python3
# instead leaves every mtime alone and watches for the thing that actually
# costs — the roster parse.
PYSTUB="$BASE/pystub"; mkdir -p "$PYSTUB"
PY_LOG="$BASE/python3.log"
cat > "$PYSTUB/python3" <<EOF
#!/bin/sh
echo "python3 \$*" >> "$PY_LOG"
exit 1
EOF
chmod +x "$PYSTUB/python3"
OUT_X2=$(run_hook "$FH" "$BASE/logx2" HANDOFF_WINDOW=seat-alpha \
         PATH="$PYSTUB:$MOCKDIR:$PATH")
if has_header "$OUT_X2"; then ok; else
  bad "X2 cache: a WARM run must still print the header (it came back empty, so the cache did not hit)"
fi
if [ ! -s "$PY_LOG" ]; then ok; else
  bad "X2b cache: a warm run must not parse the roster at all ($(head -1 "$PY_LOG"))"
fi

# X2c — the probe is not vacuous: with the cache expired (the composer itself
# is a declared dep) the SAME run does reach python3 and produces no header.
touch "$TIER/agents/lib/seat-identity.sh"
OUT_X2C=$(run_hook "$FH" "$BASE/logx2c" HANDOFF_WINDOW=seat-alpha \
          PATH="$PYSTUB:$MOCKDIR:$PATH")
if [ -s "$PY_LOG" ] && ! has_header "$OUT_X2C"; then ok; else
  bad "X2c cache: touching the composer must expire the cache (python3 log: $(wc -l < "$PY_LOG"), header printed: $(has_header "$OUT_X2C" && echo yes || echo no))"
fi
# Re-warm with a real python3 before the staleness case below.
run_hook "$FH" "$BASE/logx2d" HANDOFF_WINDOW=seat-alpha >/dev/null

# A new laurel rewrites the history file (temp + mv), which moves both the
# file's and the directory's mtime — two of the deps the composer declared.
SEATS_YML="$ROSTER" bash "$TIER/agents/lib/seat-history.sh" laurel \
  --seat seat-alpha --title "cache must expire" --bead dotfiles-fixture \
  --commit deadbee --why "written after the header was cached" \
  --date 2026-08-12 --dir "$TIER/refs/seats" >/dev/null
OUT_X3=$(run_hook "$FH" "$BASE/logx3" HANDOFF_WINDOW=seat-alpha)
if printf '%s' "$OUT_X3" | grep -qF 'cache must expire'; then ok; else
  bad "X3 cache: a laurel written after the cache must appear — the cached header went STALE"
fi

# --- Summary ---
TOTAL=$((PASS + FAIL))
if [ "$FAIL" -eq 0 ]; then
  echo "PASS: $PASS/$TOTAL test cases"
  exit 0
fi
echo "FAIL: $FAIL/$TOTAL test cases failed"
for n in "${FAILED_NAMES[@]}"; do echo "  - $n"; done
exit 1
